name: TeX

on:
  push:
    paths:
      - "tex/**.tex"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Spelling
        uses: reitermarkus/aspell@master
        with:
          files: tex/*.tex
          args: --lang en_GB --mode tex --personal ./tex/aspell.en_GB.pws --add-tex-command PassOptionsToPackage\ pp --add-tex-command texttt\ op --add-tex-command cite\ op --add-tex-command german\ p
      - name: Compile Paper
        uses: reitermarkus/latexmk@master
